export default {
  POPPINS_BLACK: 'Poppins-Black',
  POPPINS_BLACK_ITALIC: 'Poppins-BlackItalic',
  POPPINS_BOLD: 'Poppins-Bold',
  POPPINS_BOLD_ITALIC: 'Poppins-BoldItalic',
  POPPINS_EXTRA_LIGHT: 'Poppins-ExtraLight',
  POPPINS_EXTRA_BOLD: 'Poppins-ExtraBold',
  POPPINS_EXTRA_LIGHT_ITALIC: 'Poppins-ExtraLightItalic',
  POPPINS_ITALIC: 'Poppins-Italic',
  POPPINS_LIGHT_ITALIC: 'Poppins-LightItalic',
  POPPINS_LIGHT: 'Poppins-Light',
  POPPINS_MEDIUM: 'Poppins-Medium',
  POPPINS_REGULAR: 'Poppins-Regular',
  POPPINS_SEMIBOLD: 'Poppins-SemiBold',
  POPPINS_SEMIBOLD_ITALIC: 'Poppins-SemiBoldItalic',
  POPPINS_SEMIBOLD_THIN: 'Poppins-SemiBoldThin',
  POPPINS_THIN: 'Poppins-Thin',
  POPPINS_THIN_ITALIC: 'Poppins-ThinItalic',
};
