export default {
  SPLASH_SCREEN: 'SPLASH_SCREEN',
  INITIAL_SCREEN: 'INITIAL_SCREEN',
  LOGIN_RECRUITER_SCREEN: 'LOGIN_RECRUITER_SCREEN',
  SIGN_UP_RECRUITER_SCREEN: 'SIGN_UP_RECRUITER_SCREEN',
  HOME_SCREEN: 'HOME_SCREEN',
  CHAT_SCREEN: 'CHAT_SCREEN',
  SEARCH_SCREEN: 'SEARCH_SCREEN',
  POST_SCREEN: 'POST_SCREEN',
  EDIT_POST_SCREEN: 'EDIT_POST_SCREEN',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
};
