export default {
  TITLE: 'Find My Job',
  SLOGAN: 'Post & Find Job In One Place',
  HIRE_CANDIDATES: 'Want to Hire Candidate',
  GET_JOB: 'Want to Get Job',
  WHAT_ARE_YOU_LOOKING_FOR: 'What are you looking for ?',
  TITLE_FORGOT: 'Forgot Password ?',
  TITLE_LOGIN: 'Login',
  TITLE_SIGN_UP: 'Sign Up',
  TITLE_POST: 'Post Job',
  TITLE_EDIT_POST: 'Edit Post Job',
  TITLE_UPDATE_POST: 'Update Post',
  TITLE_CREATE_ACCOUNT: 'Create an account',
  TITLE_UPDATE_PROFILE: 'Update Profile',
  HIRE_EMAIL_PLACEHOLDER: 'Enter your email',
  HIRE_PASS_PLACEHOLDER: 'Enter your password',
  TITLE_NAME: 'Contact',
  TITLE_PLACE_HOLDER_EMAIL: 'ex xyz@gmail.com',
  TITLE_PLACE_HOLDER_MOBILE: '+9193434*****',
  TITLE_PLACE_HOLDER_COMPANY: 'ex google',
  TITLE_PLACE_HOLDER_ADDRESS: 'ex 105 Lost angeles usa',
  TITLE_PLACE_HOLDER_PASSWORD: 'ex **********',
};
